### ISSUE TITLE
KaTeX fraction not visible

### ISSUE THREAD

**Issue by sebp** [notable/notable#679]
- **OS Version**: macOS Mojave
- **Notable Version**: 1.5.1

### Current behavior

When using `\frac` in an equation, the line separating the numerator from the denominator is not visible for both the light and dark theme.

<img width="797" alt="example-dark" src="https://user-images.githubusercontent.com/74460/58761210-2dcfde00-8531-11e9-9b3f-dbd48fd8bd8d.png">
<img width="797" alt="example-light" src="https://user-images.githubusercontent.com/74460/58761211-2e687480-8531-11e9-9c31-88fe1bbbe672.png">

### Expected behavior

The line should have the same color as the main text.

**Comment by fabiospampinato** [comment]
Yeah the color of the `.frac-line` element should be properly styled.

Let me know if you find any other such issues 👍

**Comment by fabiospampinato** [comment]
Fixed in v1.6.

**Comment by endfreude** [comment]
This color mismatch still appears for $\underline{x}$, which adds a line under the given math expression x. I will try to find other Katex commands behaving like that.

**Comment by fabiospampinato** [comment]
@endfreude I'll make sure to fix that too, let me know if you find any other issues like that.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

I should have fixed all of these sorts of errors, hopefully there shouldn't be any others.
