### ISSUE TITLE
Support for relative paths to images stopped with release 1.6.0

### ISSUE THREAD

**Issue by ThomasBri** [notable/notable#733]
- **OS Version**: Ubuntu 16.04 and macOS Mojave 10.14.2
- **Notable Version**: 1.6.0 - 1.6.2

### Current behavior

```![](../images/test.png)``` does not show the image in the note.
Instead ```![](file:///<absolute_path>/images/test.png)``` is displayed.

### Expected behavior

Showing the image as in previous versions of Notable.

**Comment by fabiospampinato** [comment]
Is the "images" directory one that you created?

I'm not sure I'm fully understanding the issue you are having, are you saying that relative file paths must remain relative? Basically how should "![](../images/test.png)" be rendered in your opinion versus how it's rendered currently?

**Comment by ThomasBri** [comment]
Yes, I created the image directory so I can keep my images in separate subdirctories based on subject and reference them by their relative file paths in the notes, e.g. ```![](../images/test.png)```.

The issue is that before version 1.6.0 the images were correctly shown in the note if I referenced them by relative file path, but since 1.6.0 they do not appear anymore.

If I use absolute file paths, it is still working. But absolute file paths have the disadvantage that I cannot use my notes across different devices.

**Comment by xgdgsc** [comment]
It is disappointing from a new user perspective when I open the note in my other markdown editors like Typora and paste an image, it is not shown correctly inside notable.

**Comment by fabiospampinato** [comment]
Thanks for the details, this should definitely get fixed.

**Comment by fabiospampinato** [comment]
This turned out to be an upstream bug: https://github.com/markdown-it/markdown-it/issues/573

Hopefully it will be addressed soon, they are usually pretty speedy.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by ajit555db** [comment]
Installed v1.7.2.

The issue is not fixed yet.

The attachment images co-located with the file is not displaying in the notable app.  I need to put the images in attachment folder and reference it from there in the document. 

```md
This works
![](@attachment/fabric.png)

This doesn't works
![](./fabric.png)
```

**Comment by fabiospampinato** [comment]
@ajit555db 	I'll take another look at this 👍 

What OS are you on?

**Comment by bogdan-suchok** [comment]
@fabiospampinato , hi there! I just installed version 1.7.2 on Ubuntu 18.04 and can confirm the behavior @ajit555db described above. So far, I've only been able to see images via @attachment token, or if using url. 

Nice app! But that bug really prevents me from using it as lots of my notes contain images of relative paths.

Thanks.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by bogdan-suchok** [comment]
Just checked the new release, 1.7.3. The issue persists, unfortunately. What release has this issue been fixed in actually?

**Comment by fabiospampinato** [comment]
@bogdan-suchok I can't reproduce this anymore in v1.7.3 🤔 Could you post a note (or even better a data directory) that reproduces the issue for you?

**Comment by bogdan-suchok** [comment]
@fabiospampinato , sure thing. Here is my setup.

the data directory looks like this:
- notes
- attachments

Under notes, I have several subfolders. E.g., for a note in the notes/drafts subfolder, if I use this syntax: ![](./image.jpg), it doesn't appear up in the note. On the contrary, if I use syntax like ![](./drafts/image.jpg), it shows up. But with the latter, it won't appear in my mobile application (Notebooks) for the obvious reason.

Could you reproduce that and ideally fix?

Thanks,
Bogdan.

**Comment by fabiospampinato** [comment]
@bogdan-suchok I can reproduce. The issue here is that throughout the codebase we are kind of assuming that notes are in `notes/*` and attachments are in `attachments/*`, when a different structure is used there might be issue. I'll see if I can tackle them during this iteration cycle 👍

**Comment by njwedwards** [comment]
Great software BTW. This issue is a big one for me too. I have a lot of notes in standard markdown with images, and this is a bit of a showstopper at the moment.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Now relative links are resolved relative to the actual file path of the note.
