### ISSUE TITLE
crash on start when in home directory

### ISSUE THREAD

**Issue by mapclyps** [notable/notable#736]
- **OS Version**: Manjaro 18.0.4
- **Notable Version**: 1.6.2

### Current behavior

notable does not start (no window shown) and prompts the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new Conf (/opt/Notable/resources/app.asar/main.js:9:116236)
    at new ElectronStore (/opt/Notable/resources/app.asar/main.js:1:25238)
    at Module.<anonymous> (/opt/Notable/resources/app.asar/main.js:21:6036)
    at __webpack_require__ (/opt/Notable/resources/app.asar/main.js:1:150)
    at Object.<anonymous> (/opt/Notable/resources/app.asar/main.js:9:86307)
    at __webpack_require__ (/opt/Notable/resources/app.asar/main.js:1:150)
    at /opt/Notable/resources/app.asar/main.js:1:1936
    at Object.<anonymous> (/opt/Notable/resources/app.asar/main.js:1:1982)
    at Module._compile (internal/modules/cjs/loader.js:815:30)

```
whenever it is called from my users home or any of my homes subdirectories. It however starts normally when called from any other diectory.

### Expected behavior

Notable starts and opens the main Window.

**Comment by fabiospampinato** [comment]
> whenever it is called from my users home or any of my homes subdirectories. It however starts normally when called from any other diectory.

By looking at the stack trace it seems that the settings file located in `~/.notable.json` might be malformed, can you attach the file here so that I can see what's wrong? Did you edit it manually?

Removing it should fix the issue `rm ~/.notable.json`.

**Comment by mapclyps** [comment]
It seems that notable loads the file correctly when started from any other directory than my home.
I deleted the file and that does not solve the issue. The error message is also exactly the same when the file `~/.notable.json` is not present. Still, it works from anywhere else than my home and subdirs.

**Comment by fabiospampinato** [comment]
That's pretty weird. Maybe the initial file is not written properly to disk or something, can you still post the file here? Perhaps it contains some clues.

**Comment by mapclyps** [comment]
I also found it really strange, especially since no one else had this issue it seems. 
The initial file created after the initial dialog in notable contains
```
{
        "monaco": {
                "editorOptions": {
                        "minimap": {
                                "enabled": false
                        },
                        "lineNumbers": "off",
                        "scrollBeyondLastLine": false,
                        "wordWrap": "bounded"
                }
        },
        "sorting": {
                "by": "title",
                "type": "ascending"
        },
        "theme": "light",
        "tutorial": true,
        "cwd": "/home/huntemann"
}
```
is there maybe any other JSON file anywhere which is loaded by notable and which could become corrupted?
I  reinstalled notable (`/opt/Notable` was deleted after removing) but that also did not help.

**Comment by fabiospampinato** [comment]
> is there maybe any other JSON file anywhere which is loaded by notable and which could become corrupted?

No I'm using `ElectronStore` only for that file, and there aren't any other JSON files getting loaded either.

If you can reproduce the issue with v1.5.1 too then you should be able to compile your own version of the app, so that you can fire up the debugger and try to find the root cause. Alternatively I guess I can also compile a version of v1.6 with some extra `debugger;` statements in it for you.

**Comment by fabiospampinato** [comment]
> whenever it is called from my users home or any of my homes subdirectories

@mapclyps how are you calling Notable, just executing `notable` in the terminal? What package did you install, the `.deb`?

**Comment by fabiospampinato** [comment]
I can't reproduce under Ubuntu.

**Comment by mapclyps** [comment]
I had an empty `package.json` in my home. When I start notable from this directory I experience this error. It was solved once I deleted the file. Another program complained about the empty `package.json` in my home directory, otherwise I would not have noticed.

I guess notable should start in case you like to have an empty `package.json` in your home dir, even though it will probably not expect many users

**Comment by fabiospampinato** [comment]
@mapclyps interesting finding! I think then the problem comes from this line: https://github.com/sindresorhus/conf/blob/410cc144141f1467cc91fe4b16f6b7f42a8afac8/index.js#L56 it shouldn't be a problem anymore in v1.9 since we are using a different library for managing settings now.
