### ISSUE TITLE
Indented inline math (LaTeX) not rendering

### ISSUE THREAD

**Issue by JayZ2398** [notable/notable#828]
- **OS Version**: Windows 10 v1903
- **Notable Version**: 1.7.3

### Current behavior

1. Create a bulleted or ordered list.
2. Indent twice or more and try to use in line math.
3. Inline math doesn't render.

For example, paste the following text into a document.

```markdown
1. Well $\mathbb{this}$ is interesting
    - So is $\mathbb{this}$
        - But this isn't very $\mathbb{interesting}$
            - $\mathbb{Interest}$ is long gone.
```

Screenshot:
![image](https://user-images.githubusercontent.com/28042291/65381418-3c3a4380-dd34-11e9-9923-824cf8ff4e27.png)

### Expected behavior

In-line math should render regardless of the level of indentation.

**Comment by fabiospampinato** [comment]
I think the KaTeX plugin is mistakenly detecting those lines as part of a code block due to their indentation. To fix _all_ these sorts of edge cases I'll have to rewrite the plugins, implementing them as simple text replacements is too brittle.

**Comment by fabiospampinato** [comment]
In order to fix this properly I would need to rewrite all plugins in a more reliable way. It will happen but just not right now.

**Comment by JayZ2398** [comment]
Thanks for looking into it - it’s a very minor issue and I just flagged it in case you wanted to know. 😊

**Comment by fabiospampinato** [comment]
Every issue should be addressed eventual, please keep reporting them as you find them 👍

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by Ramojus** [comment]
Somehow I'm still experiencing this same issue, even with the insiders version. When a block is indented by two tabs or more, KaTeX doesn't get rendered.

**Comment by psanou** [comment]
I'm still also experiencing this same issue.

**Comment by fabiospampinato** [comment]
@ramojus @psanou could you post some example markdown that reproduces the problem?

**Comment by psanou** [comment]
I hope this example can illustrate the problem
```
# Untitled (5)

1. This is the first level. The problem occurs after two tabulations
    - if it is a bullet point $\rightarrow$ work!

2. But if i want to make go back to the line in the same point
  one tabulation will $work$
    two tabulations will $fail$ 

3. level 1
    - **Title**: 
      $\cdots$
```

**Comment by symbolisticism** [comment]
I am having the same issue in Google Colab. This is the LaTeX that is not rendering:

```
* ```abs```
    - **Domain:** $y=mx+b$ 
```
