### ISSUE TITLE
Checkboxes not working as expected

### ISSUE THREAD

**Issue by renanwillian** [notable/notable#885]
- **OS Version**: Windows 10
- **Notable Version**: 1.8

### Current behavior
I have a note with multiple checkbox in a list:
```
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
```

When I click the first checkbox, the second one get checked instead, and I'm unable to uncheck it.

![checkbox issue](https://user-images.githubusercontent.com/30376796/68419274-adb14280-0178-11ea-9f30-a86e179d8e7e.gif)

### Expected behavior
It should only check and uncheck the clicked checkbox.

**Comment by WilliamSBunin** [comment]
Appears to happen if you have 2 blank lines in front of code

Works correctly
````
# test

- [ ] 1
- [x] 2
- [x] 3
- [ ] 4
````

Works incorrectly...
````
# test


- [ ] 1
- [x] 2
- [ ] 3
- [x] 4
````

**Comment by renanwillian** [comment]
I tested both ways and none of them worked as expected:

![checkbox issue 2](https://user-images.githubusercontent.com/30376796/68428412-e2c69080-018a-11ea-8002-5425096a348e.gif)

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by WilliamSBunin** [comment]
In 1.8.1, I can still reproduce this error when there are multiple lines above the checkbox code.

@renanwillian, how about you?

**Comment by fabiospampinato** [comment]
@WilliamSBunin That might be a different issue, could you post a note that reproduces the problem?

**Comment by renanwillian** [comment]
Yes, the bug persists when two or more blank lines are above the checkbox.

```
# test


- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
```

![checkbox issue 3](https://user-images.githubusercontent.com/30376796/68593337-f700db00-0473-11ea-8470-0389220dc673.gif)

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

There was an issue with vertical whitespaces getting matches when horizontal whitespaces were actually what we needed to match, so for instance 3 consecutive newlines might get interpreted as the beginning of a codeblock.
