### ISSUE TITLE
Startup crash: "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by khalidwilliams** [notable/notable#934]
- **OS Version**: macOS Mojave 10.14.6
- **Notable Version**: 1.8.2

### Current behavior

After updating from 1.8.1 to 1.8.2, I get this error on startup:
<img width="413" alt="Screen Shot 2019-12-03 at 9 36 05 AM" src="https://user-images.githubusercontent.com/36432040/70070759-5d7ba380-15b1-11ea-8e81-4ec132514d15.png">

The app never opens past this message, and it happens every time I try and open Notable. I reinstalled using homebrew, and still get the same issue. 

May be related to #922 

### Expected behavior

Expected behavior is a normal start up.

**Comment by fabiospampinato** [comment]
@khalidwilliams Could you post here the content of your `~/.notable.json` file? 

Also deleting it and reopening the app should fix the issue.

**Comment by fabiospampinato** [comment]
This is an issue which the future settings library I'll use is already prepared to handle gracefully: https://github.com/fabiospampinato/configuration.

So I'd just close this in favor of #476.

**Comment by khalidwilliams** [comment]
@fabiospampinato Thanks for following up. My `~/.notable.json` is as follows:
```
{
	"monaco": {
		"editorOptions": {
			"minimap": {
				"enabled": false
			},
			"lineNumbers": "off",
			"scrollBeyondLastLine": false,
			"wordWrap": "bounded"
		}
	},
	"sorting": {
		"by": "title",
		"type": "ascending"
	},
	"theme": "dark",
	"tutorial": true,
	"cwd": "/Users/khalidwilliams/.notable"
}
```

I deleted the `~/.notable.json` file and am still receiving the same error.  Is there any time frame on when the settings library will be complete?

**Comment by fabiospampinato** [comment]
@khalidwilliams The library is complete already, and available [here](https://github.com/fabiospampinato/configuration), I want to start using it in v1.9.

---

The JSON file you posted seems alright though, so I don't understand where the issue is coming from, I'll have to take a closer look at this.

**Comment by fabiospampinato** [comment]
@khalidwilliams if you're still interested in having me fix this I can build you a special version of the app that logs somewhere the configuration file it's trying to read. Since the one you posted here looks alright, and the app doesn't work when you start it from other paths, I think maybe for some reason the app sometimes tries to load a different file than the one you posted here, and that file for some reason doesn't contain well-formed JSON. 

Do you want to install this patched version of the app so that you can help me debug this?

**Comment by khalidwilliams** [comment]
@fabiospampinato that'd be great! I'm happy to help figure this out however I can. What would I need to do to download the patch?

**Comment by fabiospampinato** [comment]
@khalidwilliams you can download the patched version here: https://drive.google.com/open?id=1IhEeCPE-Pd0ryJtOe9NiG2_1_Eq4bws1 . You'll probably want to revert to v1.8.2 after trying it though.

It should now tell you which file it's attempting to read, let me know if you see any strange paths or if the paths are pointing to files containing malformed JSON.

<img width="718" alt="Screen Shot 2020-01-14 at 17 32 20" src="https://user-images.githubusercontent.com/1812093/72367957-0959f800-36f5-11ea-99e9-887c442656e1.png">

**Comment by fabiospampinato** [comment]
Duplicate of #736. @khalidwilliams let me know if the build I made for you has provided any useful insight.
